Bump activesupport from 7.1.3.4 to 7.1.4 (#87)
Bumps [activesupport](https://github.com/rails/rails) from 7.1.3.4 to 7.1.4.
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a href="https://github.com/rails/rails/releases">activesupport's releases</a>.</em></p>
<blockquote>
<h2>7.1.4</h2>
<h2>Active Support</h2>
<ul>
<li>
<p>Improve compatibility for <code>ActiveSupport::BroadcastLogger</code>.</p>
<p><em>Máximo Mussini</em></p>
</li>
<li>
<p>Pass options along to write_entry in handle_expired_entry method.</p>
<p><em>Graham Cooper</em></p>
</li>
<li>
<p>Fix Active Support configurations deprecations.</p>
<p><em>fatkodima</em></p>
</li>
<li>
<p>Fix teardown callbacks.</p>
<p><em>Tristan Starck</em></p>
</li>
<li>
<p><code>BacktraceCleaner</code> silence core internal methods by default.</p>
<p><em>Jean Boussier</em></p>
</li>
<li>
<p>Fix <code>delegate_missing_to allow_nil: true</code> when called with implict self</p>
<pre lang="ruby"><code>class Person
  delegate_missing_to :address, allow_nil: true
<p>def address<br />
nil<br />
end</p>
<p>def berliner?<br />
city == &quot;Berlin&quot;<br />
end<br />
end</p>
<p>Person.new.city # =&gt; nil<br />
Person.new.berliner? # undefined local variable or method `city' for an instance of Person (NameError)<br />
</code></pre></p>
<p><em>Jean Boussier</em></p>
</li>
<li>
<p>Work around a Ruby bug that can cause a VM crash.</p>
<p>This would happen if using <code>TaggerLogger</code> with a Proc
formatter on which you called <code>object_id</code>.</p>
</li>
</ul>
<!-- raw HTML omitted -->
</blockquote>
<p>... (truncated)</p>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a href="https://github.com/rails/rails/commit/6f57590388ca38ed2b83bc1207a8be13a9ba2aef"><code>6f57590</code></a> Preparing for 7.1.4 release</li>
<li><a href="https://github.com/rails/rails/commit/63fe89d0f5ee949f316c50c0bd1b3494ae5ec397"><code>63fe89d</code></a> Sync changelog</li>
<li><a href="https://github.com/rails/rails/commit/128b5b03babbdd0dd0d0e2fb224f956aef92ad2e"><code>128b5b0</code></a> Merge pull request <a href="https://redirect.github.com/rails/rails/issues/52631">#52631</a> from zenspider/zenspider/minitest-cleanup</li>
<li><a href="https://github.com/rails/rails/commit/dbc560d7b1f4c7463b0140fcacd2be5f8e10be56"><code>dbc560d</code></a> Merge pull request <a href="https://redirect.github.com/rails/rails/issues/52609">#52609</a> from rails/rm-minitest</li>
<li><a href="https://github.com/rails/rails/commit/5141c148d9c97b62a777690b8863799f9826438d"><code>5141c14</code></a> Fix <code>delegate_missing_to allow_nil: true</code> when called with implict self</li>
<li><a href="https://github.com/rails/rails/commit/a2a12fc2e3f4e6d06f81d4c74c88f8e6b3369ee6"><code>a2a12fc</code></a> Fix a performance regression in attribute methods</li>
<li><a href="https://github.com/rails/rails/commit/aa418a04ba9987170285ec000386494ec80c848b"><code>aa418a0</code></a> Merge pull request <a href="https://redirect.github.com/rails/rails/issues/52099">#52099</a> from justinko/issue-52089</li>
<li><a href="https://github.com/rails/rails/commit/eedbe69470962e2ac1fb91913b8104a0c873d17a"><code>eedbe69</code></a> Merge branch '7-1-sec' into 7-1-stable</li>
<li><a href="https://github.com/rails/rails/commit/e2d8ca84dc67e189ccb9b9543d993f6ee7bd49de"><code>e2d8ca8</code></a> Update Method#duplicable? to be consistent with Ruby 3.4</li>
<li><a href="https://github.com/rails/rails/commit/8dd08eb0440b8944b2f3f28745e396d26a9f9b6a"><code>8dd08eb</code></a> Merge pull request <a href="https://redirect.github.com/rails/rails/issues/51939">#51939</a> from ElMassimo/fix-broadcast-logger-compatibility</li>
<li>Additional commits viewable in <a href="https://github.com/rails/rails/compare/v7.1.3.4...v7.1.4">compare view</a></li>
</ul>
</details>
<br />


[![Dependabot compatibility score](https://dependabot-badges.githubapp.com/badges/compatibility_score?dependency-name=activesupport&package-manager=bundler&previous-version=7.1.3.4&new-version=7.1.4)](https://docs.github.com/en/github/managing-security-vulnerabilities/about-dependabot-security-updates#about-compatibility-scores)

Dependabot will resolve any conflicts with this PR as long as you don't alter it yourself. You can also trigger a rebase manually by commenting `@dependabot rebase`.

[//]: # (dependabot-automerge-start)
[//]: # (dependabot-automerge-end)

---

<details>
<summary>Dependabot commands and options</summary>
<br />

You can trigger Dependabot actions by commenting on this PR:
- `@dependabot rebase` will rebase this PR
- `@dependabot recreate` will recreate this PR, overwriting any edits that have been made to it
- `@dependabot merge` will merge this PR after your CI passes on it
- `@dependabot squash and merge` will squash and merge this PR after your CI passes on it
- `@dependabot cancel merge` will cancel a previously requested merge and block automerging
- `@dependabot reopen` will reopen this PR if it is closed
- `@dependabot close` will close this PR and stop Dependabot recreating it. You can achieve the same result by closing it manually
- `@dependabot show <dependency name> ignore conditions` will show all of the ignore conditions of the specified dependency
- `@dependabot ignore this major version` will close this PR and stop Dependabot creating any more for this major version (unless you reopen the PR or upgrade to it yourself)
- `@dependabot ignore this minor version` will close this PR and stop Dependabot creating any more for this minor version (unless you reopen the PR or upgrade to it yourself)
- `@dependabot ignore this dependency` will close this PR and stop Dependabot creating any more for this dependency (unless you reopen the PR or upgrade to it yourself)


</details>